name: Deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Docs Repo
              uses: actions/checkout@v3
              with:
                  path: 'athena-docs'

            - name: Clone Athena Markdown API
              uses: actions/checkout@v3
              with:
                  repository: 'stuyk/altv-athena'
                  ref: 'gh-pages'
                  path: 'altv-athena'

            - name: 'Clean Old API Docs'
              run: |
                  rm -rf ./athena-docs/docs/api/classes
                  rm -rf ./athena-docs/docs/api/enums
                  rm -rf ./athena-docs/docs/api/interfaces
                  rm -rf ./athena-docs/docs/api/modules

            - name: 'Move New API Docs'
              run: |
                  mv ./altv-athena/classes ./athena-docs/docs/api/classes
                  mv ./altv-athena/enums ./athena-docs/docs/api/enums
                  mv ./altv-athena/interfaces ./athena-docs/docs/api/interfaces
                  mv ./altv-athena/modules ./athena-docs/docs/api/modules

            - name: 'Install NodeJS'
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install Docs
              working-directory: 'athena-docs'
              run: npm install

            - name: Build Docs
              working-directory: 'athena-docs'
              run: npm run build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: athena-docs/docs/.vitepress/dist
                  cname: athenaframework.com
